# -*- coding: utf-8 -*-
"""Data Exploration code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nO9qFCPX-wtS7JMDMP0-5_38EbtEvQWC
"""



# Step 1: Upload the CSV file
from google.colab import files
uploaded = files.upload()

import pandas as pd

# Assuming the file was uploaded using files.upload()
# it will be available in the current working directory
# you can find the current working directory using: !pwd
# and list files using: !ls

file_name = list(uploaded.keys())[0] # Get the name of the uploaded file
df = pd.read_csv(file_name) # Read the file directly

# If the file is in a specific location, replace 'file_name' with the actual path.
# For example:
# file_path = '/content/student-dataset.csv'
# df = pd.read_csv(file_path)

# Display the first few rows
print("First 5 rows of the dataset:")
print(df.head())

# General info
print("\nDataset Info:")
df.info()

# Statistical summary
print("\nSummary Statistics:")
print(df.describe())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Select only numeric features for histogram
numeric_df = df.select_dtypes(include=['number', 'datetime'])

# Check if there are any numeric features
if len(numeric_df.columns) > 0:
  # Histogram of numeric features
  numeric_df.hist(bins=20, figsize=(14, 10))
  plt.tight_layout()
  plt.show()
else:
  print("No numeric or datetime columns found for histogram.")

# Correlation heatmap for numeric features
if len(numeric_df.columns) > 1: # Check for at least 2 numeric features for correlation
  plt.figure(figsize=(10, 8))
  sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
  plt.title("Correlation Heatmap")
  plt.show()
else:
  print("Not enough numeric or datetime columns to create a correlation heatmap.")


# Pairplot for numeric features (if dataset is not too large)
# sns.pairplot(numeric_df, hue='target_column_name') # Replace with your actual target column if labeled
# plt.show()

import pandas as pd

# Assuming the file was uploaded using files.upload() in current directory
# you can check it using !ls

try:
  df = pd.read_csv("student-dataset.csv", sep=';')  # Using semicolon as separator
except FileNotFoundError:
  print("File not found in the current directory. Please upload it using files.upload().")

  from google.colab import files
  uploaded = files.upload()
  file_name = list(uploaded.keys())[0]
  df = pd.read_csv(file_name, sep=';')  # Using semicolon as separator

# Check dataset structure and data types
print("Dataset Info:\n")
print(df.info())

# Display first few rows
print("\nFirst few rows:\n")
print(df.head())

# Count missing values per column
print("\nMissing Values:\n")
print(df.isnull().sum())

# Display numerical summary of the dataset
print("\nSummary Statistics:\n")
print(df.describe())

# Count unique values in each column
print("\nUnique Values per Column:\n")
print(df.nunique())

# Display value counts for categorical columns
categorical_columns = ['sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian']
for column in categorical_columns:
    print(f"\nValue counts for {column}:\n")
    print(df[column].value_counts())